# Site settings
title: Stellar
subtitle: by HTML5 UP
description: >- # this means to ignore newlines until "baseurl:"
  A responsive site template designed by HTML5 Up<br>
  and released under the Creative Commons.

# Contact information
street_address: 1234 Somewhere Road
city: Nashville
state: TN
zip_code: 55555
country: United States of America
phone: (716) 555-5555
email: youremailaddress@gmail.com

# Social settings
500px_url:
facebook_url:
github_url: https://github.com/apehex
gitlab_url:
googleplus_url:
instagram_url: https://instagram.com
linkedin_url: https://www.linkedin.com
pinterest_url:
slack_url:
twitter_url: https://twitter.com

# Collections
collections:
  home_sections:
    output: false

# Build settings
markdown: kramdown
sass:
  style: compressed

# Publication settings
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://apehex.github.io/jekyll-theme-stellar" # the base hostname & protocol for your site, e.g. http://example.com
author: apehex

# Exclude from processing
